on: [push, pull_request]

name: Check

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Check
        run: cargo check --all-features --verbose